# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lomi' do
  platform :ios, '14.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'LomiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LomiUITests' do
    # Pods for testing
  end

  pod 'Alamofire'

  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  
  # add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics', '~> 9.0'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  # add the ESPProvision for sending the user's wifi credential to the IoT device
  # https://github.com/espressif/esp-idf-provisioning-ios
  pod 'ESPProvision'

end
