name: Unit Tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  Run-Unit-Tests:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v2
      
      - name: Install xcpretty
        run: gem install xcpretty --install-dir ./gems xcpretty

      - name: Install cocoapods
        run: gem install cocoapods --install-dir ./gems cocoapods

      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: gems/bin/pod install

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build and Test
        run: xcodebuild clean test -workspace Lomi/Lomi.xcworkspace -scheme Lomi -destination 'platform=iOS Simulator,name=iPhone 13' | gems/bin/xcpretty -c && exit ${PIPESTATUS[0]} 